opensourceframework.env.logger.workdir: ../../logs

# swagger相关配置
# 注意：
#     需手动修改的配置
#     basePackage属性：需修改为rest包所在的全限定路径（通常只需将xxx替换为中心的英文名即可）
#     title属性：       将xxx修改为对应中心的中文名即可。（生成的swagger文档的标题）
#     description属性： 将xxx修改为对应中心的中文名即可。（生成的swagger文档的描述）
opensourceframework.swagger:
      enable: true
      basePackage: org.opensourceframework
      title: opensources-demo-es API
      description: opensources-demo-es API
      version: 1.0.0

opensourceframework.es.registryvo:
      # 192.168.0.100:9200,192.168.0.101:9200,192.168.0.102:9200
      serverHosts: 127.0.0.1:9200
      scanPath: org.opensourceframework.user.es.eo
      userName:
      passWord:
