server:
  port: 0
grpc:
  server:
    port: 0
spring:
  application:
    name: opensources-user-grpc-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.53.157.115:8848
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator info
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8
    name:opensources-user-grpc-provider
